//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServiceGinfesImplBinding", Namespace="http://homologacao.ginfes.com.br")]
public interface IServiceGinfesImplBinding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string CancelarNfse(string arg0);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string CancelarNfseV3(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string CancelarNfseV4(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarLoteRps(string arg0);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarLoteRpsV3(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarLoteRpsV4(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarNfse(string arg0);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarNfsePorRps(string arg0);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarNfsePorRpsV3(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarNfsePorRpsV4(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarNfseV3(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarNfseV4(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarSituacaoLoteRps(string arg0);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarSituacaoLoteRpsV3(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string ConsultarSituacaoLoteRpsV4(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string RecepcionarLoteRps(string arg0);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string RecepcionarLoteRpsV3(string arg0, string arg1);
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://homologacao.ginfes.com.br", ResponseNamespace="http://homologacao.ginfes.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    string RecepcionarLoteRpsV4(string arg0, string arg1);
}
